#!/usr/bin/env bash

set -e

usage() {
    echo "Object: The Script was designed to install R packages on terminal of Unix."
    echo "Note: First install R"
    echo "Developer: Shuangbin Xu"
    echo "Email: xshuangbin@163.com"
    echo
    echo "Usage: $0 <-c/-b> <-i names>"
    echo "  [-c CRAN]            - if the packages is from CRAN."
    echo "  [-b BIOCONDUCTOR]    - if the packages is from Bioconductor."
    echo "  [-i names]           - The names of R packages, The comma should be used for multiple packages."
    echo "  [-t threads]         - the number of thread, default is 2."
    echo "  [-n nolock]          - using --no-lock to install."
}

Rname=""

while getopts ":i:t:ncbh" Option
    do
    case $Option in
        i) Rname=$OPTARG ;;
        t) Ncpus=$OPTARG ;;
        c) ACTION=CRAN ;;
        b) ACTION=BIOCONDUCTOR ;;
        n) ACTION2=NOLOCK ;;
        h) usage ; exit -1 ;;
	*) echo "unrecognized argument. use '-h' for usage information."; exit -1 ;;
    esac
    done

shift $(($OPTIND - 1))

if [ -z "$Rname" ]; then
    echo "Error: The names of packages should be provided." >&2
    usage
fi

if [ -z "$Ncpus" ]; then
    $Ncpus=2
fi

lenRname=$(echo $Rname | awk -F "," '{print NF}')

if (( $lenRname>1 )); then
    tmp=$(echo $Rname | awk -F "," '{for(i=1;i<=NF-1;i++) printf("\"%s\",", $i);printf("\"%s\"", $NF)}')
    Rname='c('$tmp')'
else
    Rname='"'$Rname'"'
fi

craninstall() {
    Rscript -e 'install.packages('$Rname', Ncpus='$Ncpus')'
}

craninstall2(){
    Rscript -e 'install.packages('$Rname', INSTALL_opts="--no-lock", Ncpus='$Ncpus')'
}

Biocinstall() {
    Rscript -e 'BiocManager::install('$Rname', Ncpus='$Ncpus')'
}

Biocinstall2(){
    Rscript -e 'BiocManager::install('$Rname', INSTALL_opts="--no-lock", Ncpus='$Ncpus')'
}

case $ACTION+$ACTION2 in
    CRAN+) craninstall ;;
    BIOCONDUCTOR+) Biocinstall ;;
    CRAN+NOLOCK) craninstall2 ;;
    BIOCONDUCTOR+NOLOCK) Biocinstall2 ;;
esac
